apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: demoservice
        image: gcr.io/dynatrace-dev-on-demand/florian-demoservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 20m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 25Mi
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 15
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 15
          httpGet:
            path: /healthz
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: ClusterIP
  selector:
    app: service1
  ports:
  - name: http
    port: 8080
    targetPort: 8080